spring.application.name=ecommerce

# NÃO VERSIONAMOS ESSAS INFORMAÇÕES!
# Conexão com o Postgres no Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/vendasdb
spring.datasource.username=admin
spring.datasource.password=<sua_senha>

# Mostra o SQL gerado no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Cria/atualiza as tabelas automaticamente com base nas classes
spring.jpa.hibernate.ddl-auto=update